/**
 * Bộ Giáo Dục & Đào Tạo (MOET) - Chương Trình Tiếng Anh THCS (Lớp 6, 7, 8, 9)
 * Chuẩn SGK Global Success (Bộ Kết Nối Tri Thức Với Cuộc Sống / Chương trình GDPT 2018)
 * Danh mục chuẩn 12 Unit / Khối lớp với đầy đủ tên bài học, chủ điểm ngữ pháp và từ vựng.
 */

export interface UnitCurriculum {
  unitNumber: number;
  title: string;
  vietnameseTitle: string;
  grammarTopics: string[];
  grammarSummaryVi: string;
  vocabularyTheme: string;
}

export const MOET_CURRICULUM: Record<number, UnitCurriculum[]> = {
  6: [
    {
      unitNumber: 1,
      title: "My New School",
      vietnameseTitle: "Trường học mới của tôi",
      grammarTopics: ["The Present Simple", "Adverbs of Frequency"],
      grammarSummaryVi: "Thì Hiện tại đơn & Trạng từ chỉ tần suất (always, usually, often...)",
      vocabularyTheme: "School items and classroom activities",
    },
    {
      unitNumber: 2,
      title: "My House",
      vietnameseTitle: "Ngôi nhà của tôi",
      grammarTopics: ["Possessive Case ('s)", "Prepositions of Place"],
      grammarSummaryVi: "Sở hữu cách ('s) & Giới từ chỉ vị trí (in, on, under, behind, next to...)",
      vocabularyTheme: "Types of house, rooms and furniture",
    },
    {
      unitNumber: 3,
      title: "My Friends",
      vietnameseTitle: "Bạn bè của tôi",
      grammarTopics: ["The Present Continuous for future and ongoing actions"],
      grammarSummaryVi: "Thì Hiện tại tiếp diễn diễn tả hành động đang diễn ra và kế hoạch tương lai",
      vocabularyTheme: "Body parts and personality adjectives",
    },
    {
      unitNumber: 4,
      title: "My Neighbourhood",
      vietnameseTitle: "Khu phố của tôi",
      grammarTopics: ["Comparative Adjectives"],
      grammarSummaryVi: "So sánh hơn của tính từ ngắn và tính từ dài (-er / more + adj)",
      vocabularyTheme: "Places in a neighbourhood and neighbourhood adjectives",
    },
    {
      unitNumber: 5,
      title: "Natural Wonders of Viet Nam",
      vietnameseTitle: "Kỳ quan thiên nhiên Việt Nam",
      grammarTopics: ["Countable and Uncountable Nouns", "Modal Verbs: Must / Mustn't"],
      grammarSummaryVi: "Danh từ đếm được / không đếm được & Động từ khuyết thiếu Must / Mustn't",
      vocabularyTheme: "Natural wonders and travel items",
    },
    {
      unitNumber: 6,
      title: "Our Tet Holiday",
      vietnameseTitle: "Ngày lễ Tết của chúng ta",
      grammarTopics: ["Modal Verbs: Should / Shouldn't", "Some / Any for quantity"],
      grammarSummaryVi: "Động từ khuyết thiếu Should / Shouldn't & Lượng từ Some / Any",
      vocabularyTheme: "Tet activities, food and traditions",
    },
    {
      unitNumber: 7,
      title: "Television",
      vietnameseTitle: "Truyền hình",
      grammarTopics: ["Conjunctions (and, but, although, because, so)", "Question Words (Wh-words)"],
      grammarSummaryVi: "Liên từ ghép câu & Từ để hỏi (What, Where, When, Why, How...)",
      vocabularyTheme: "TV programmes and adjectives describing programmes",
    },
    {
      unitNumber: 8,
      title: "Sports and Games",
      vietnameseTitle: "Thể thao và trò chơi",
      grammarTopics: ["The Past Simple (Regular and Irregular Verbs)", "Imperatives"],
      grammarSummaryVi: "Thì Quá khứ đơn (Động từ to be & thường) & Câu mệnh lệnh",
      vocabularyTheme: "Sports, games and equipment",
    },
    {
      unitNumber: 9,
      title: "Cities of the World",
      vietnameseTitle: "Các thành phố trên thế giới",
      grammarTopics: ["Possessive Adjectives", "Possessive Pronouns"],
      grammarSummaryVi: "Tính từ sở hữu (my, your...) & Đại từ sở hữu (mine, yours...)",
      vocabularyTheme: "City landmarks and weather adjectives",
    },
    {
      unitNumber: 10,
      title: "Our Houses in the Future",
      vietnameseTitle: "Ngôi nhà tương lai của chúng ta",
      grammarTopics: ["Future Simple: Will / Won't", "Might / Might not for possibility"],
      grammarSummaryVi: "Thì Tương lai đơn (Will / Won't) & Khả năng xảy ra (Might)",
      vocabularyTheme: "Future houses and smart appliances",
    },
    {
      unitNumber: 11,
      title: "Our Greener World",
      vietnameseTitle: "Thế giới xanh hơn của chúng ta",
      grammarTopics: ["Articles: A / An / The", "First Conditional (If + Present Simple, will + V)"],
      grammarSummaryVi: "Mạo từ (a/an/the) & Câu điều kiện loại 1 (If loại 1)",
      vocabularyTheme: "Environmental protection and 3Rs (Reduce, Reuse, Recycle)",
    },
    {
      unitNumber: 12,
      title: "Robots",
      vietnameseTitle: "Người máy",
      grammarTopics: ["Superlative Adjectives", "Modal Verbs: Could / Couldn't"],
      grammarSummaryVi: "So sánh nhất của tính từ (-est / the most) & Động từ khuyết thiếu Could",
      vocabularyTheme: "Types of robots and daily robot abilities",
    },
  ],
  7: [
    {
      unitNumber: 1,
      title: "Hobbies",
      vietnameseTitle: "Sở thích",
      grammarTopics: ["The Present Simple", "Verbs of liking / disliking + V-ing"],
      grammarSummaryVi: "Thì Hiện tại đơn & Động từ chỉ sự yêu thích + V-ing (like, love, enjoy...)",
      vocabularyTheme: "Hobbies and action verbs",
    },
    {
      unitNumber: 2,
      title: "Healthy Living",
      vietnameseTitle: "Lối sống lành mạnh",
      grammarTopics: ["Simple Sentences and Compound Sentences (and, but, or, so)"],
      grammarSummaryVi: "Câu đơn và câu ghép với liên từ đẳng lập (and, but, or, so)",
      vocabularyTheme: "Health problems and healthy habits",
    },
    {
      unitNumber: 3,
      title: "Community Service",
      vietnameseTitle: "Phục vụ cộng đồng",
      grammarTopics: ["The Past Simple"],
      grammarSummaryVi: "Thì Quá khứ đơn diễn tả hành động đã hoàn tất trong quá khứ",
      vocabularyTheme: "Volunteer activities and community work",
    },
    {
      unitNumber: 4,
      title: "Music and Arts",
      vietnameseTitle: "Âm nhạc và nghệ thuật",
      grammarTopics: ["Comparisons: (not) as ... as", "The same as / Different from"],
      grammarSummaryVi: "So sánh bằng ((not) as...as), Giống như (the same as), Khác với (different from)",
      vocabularyTheme: "Music, art forms and musical instruments",
    },
    {
      unitNumber: 5,
      title: "Food and Drink",
      vietnameseTitle: "Thức ăn và đồ uống",
      grammarTopics: ["Countable and Uncountable Nouns", "Quantifiers: some, any, how much, how many, lots of"],
      grammarSummaryVi: "Danh từ đếm được / không đếm được & Lượng từ (some, any, how much, how many)",
      vocabularyTheme: "Food, drinks, ingredients and cooking verbs",
    },
    {
      unitNumber: 6,
      title: "A Visit to a School",
      vietnameseTitle: "Thăm quan trường học",
      grammarTopics: ["Prepositions of Time and Place (at, in, on)"],
      grammarSummaryVi: "Giới từ chỉ thời gian và địa điểm (at, in, on)",
      vocabularyTheme: "School facilities and historical school subjects",
    },
    {
      unitNumber: 7,
      title: "Traffic",
      vietnameseTitle: "Giao thông",
      grammarTopics: ["It indicating distance", "Modal Verb: Should / Shouldn't for advice"],
      grammarSummaryVi: "Cấu trúc 'It is... from... to...' chỉ khoảng cách & Should/Shouldn't khuyên bảo",
      vocabularyTheme: "Means of transport and road safety rules",
    },
    {
      unitNumber: 8,
      title: "Films",
      vietnameseTitle: "Phim ảnh",
      grammarTopics: ["Connectors of Contrast: Although / Though / Even though vs However / Nevertheless"],
      grammarSummaryVi: "Liên từ và trạng từ chỉ sự tương phản (Although/Even though vs However)",
      vocabularyTheme: "Types of films and film review adjectives",
    },
    {
      unitNumber: 9,
      title: "Festivals around the World",
      vietnameseTitle: "Lễ hội trên thế giới",
      grammarTopics: ["Yes/No Questions and Wh-Questions", "Adverbial phrases"],
      grammarSummaryVi: "Câu hỏi Yes/No, câu hỏi có từ để hỏi & Cụm trạng ngữ",
      vocabularyTheme: "Types of festivals and festival activities",
    },
    {
      unitNumber: 10,
      title: "Energy Sources",
      vietnameseTitle: "Các nguồn năng lượng",
      grammarTopics: ["The Present Continuous for future arrangements"],
      grammarSummaryVi: "Thì Hiện tại tiếp diễn diễn tả sự sắp xếp, kế hoạch trong tương lai",
      vocabularyTheme: "Renewable and non-renewable energy sources",
    },
    {
      unitNumber: 11,
      title: "Travelling in the Future",
      vietnameseTitle: "Phương tiện tương lai",
      grammarTopics: ["Future Simple: Will / Won't", "Possessive Pronouns"],
      grammarSummaryVi: "Thì Tương lai đơn (Will) & Đại từ sở hữu (mine, yours, his, hers, ours, theirs)",
      vocabularyTheme: "Future transportation and eco-friendly vehicles",
    },
    {
      unitNumber: 12,
      title: "English-Speaking Countries",
      vietnameseTitle: "Các nước nói tiếng Anh",
      grammarTopics: ["Articles: A / An / The / Zero Article"],
      grammarSummaryVi: "Mạo từ xác định (the), không xác định (a/an) và không dùng mạo từ",
      vocabularyTheme: "Countries, national flags and cultural attractions",
    },
  ],
  8: [
    {
      unitNumber: 1,
      title: "Leisure Time",
      vietnameseTitle: "Thời gian rảnh rỗi",
      grammarTopics: ["Verbs of liking / disliking + Gerunds / To-infinitives"],
      grammarSummaryVi: "Động từ chỉ sở thích theo sau bởi danh động từ (V-ing) hoặc động từ nguyên mẫu (To V)",
      vocabularyTheme: "Leisure activities and DIY projects",
    },
    {
      unitNumber: 2,
      title: "Life in the Countryside",
      vietnameseTitle: "Cuộc sống ở nông thôn",
      grammarTopics: ["Comparative Forms of Adverbs"],
      grammarSummaryVi: "So sánh hơn của trạng từ (more + adv / adv-er: more quickly, faster, better...)",
      vocabularyTheme: "Countryside life and agricultural activities",
    },
    {
      unitNumber: 3,
      title: "Teenagers",
      vietnameseTitle: "Thanh thiếu niên",
      grammarTopics: ["Compound Sentences & Complex Sentences with Adverbial Clauses"],
      grammarSummaryVi: "Câu ghép & Câu phức với trạng từ liên kết (however, therefore, otherwise...)",
      vocabularyTheme: "Teen clubs, social media and peer pressure",
    },
    {
      unitNumber: 4,
      title: "Ethnic Groups of Viet Nam",
      vietnameseTitle: "Các dân tộc Việt Nam",
      grammarTopics: ["Yes/No Questions and Wh-Questions", "Articles (a, an, the, zero article)"],
      grammarSummaryVi: "Câu hỏi Yes/No, câu hỏi Wh- & Mạo từ với danh từ số ít / số nhiều / không đếm được",
      vocabularyTheme: "Ethnic traditions, costumes and traditional houses",
    },
    {
      unitNumber: 5,
      title: "Our Customs and Traditions",
      vietnameseTitle: "Phong tục và truyền thống của chúng ta",
      grammarTopics: ["Modal Verbs: Should / Shouldn't & Have to / Don't have to"],
      grammarSummaryVi: "Động từ khuyết thiếu: Should/Shouldn't (khuyên) & Have to / Don't have to (bắt buộc)",
      vocabularyTheme: "Customs, family traditions and table manners",
    },
    {
      unitNumber: 6,
      title: "Lifestyles",
      vietnameseTitle: "Lối sống",
      grammarTopics: ["Future Simple (Will) & First Conditional (If loại 1)"],
      grammarSummaryVi: "Thì Tương lai đơn và Câu điều kiện loại 1 diễn tả sự việc có thể xảy ra ở hiện tại / tương lai",
      vocabularyTheme: "Traditional and modern lifestyles, habits",
    },
    {
      unitNumber: 7,
      title: "Environmental Protection",
      vietnameseTitle: "Bảo vệ môi trường",
      grammarTopics: ["Complex Sentences with Adverbial Clauses of Time (when, while, before, after, until, as soon as)"],
      grammarSummaryVi: "Mệnh đề trạng ngữ chỉ thời gian (when, while, before, after, until, as soon as)",
      vocabularyTheme: "Flora, fauna, pollution types and habitats",
    },
    {
      unitNumber: 8,
      title: "Shopping",
      vietnameseTitle: "Mua sắm",
      grammarTopics: ["The Present Simple for timetable / future events", "Adverbs of Frequency"],
      grammarSummaryVi: "Thì Hiện tại đơn diễn tả lịch trình thời gian biểu & Trạng từ tần suất",
      vocabularyTheme: "Shopping places, discounts, bargains and online shopping",
    },
    {
      unitNumber: 9,
      title: "Natural Disasters",
      vietnameseTitle: "Thiên tai",
      grammarTopics: ["The Past Continuous", "Past Continuous with When and While"],
      grammarSummaryVi: "Thì Quá khứ tiếp diễn (was/were + V-ing) & Phối hợp thì với When / While",
      vocabularyTheme: "Natural disasters, warnings and emergency responses",
    },
    {
      unitNumber: 10,
      title: "Communication in the Future",
      vietnameseTitle: "Giao tiếp trong tương lai",
      grammarTopics: ["Prepositions of Time (at, in, on, by, until, from...to...)", "Possessive Pronouns"],
      grammarSummaryVi: "Giới từ chỉ thời gian và Đại từ sở hữu",
      vocabularyTheme: "Telepathy, holography, translation machines and communication tech",
    },
    {
      unitNumber: 11,
      title: "Science and Technology",
      vietnameseTitle: "Khoa học và công nghệ",
      grammarTopics: ["Reported Speech: Statements"],
      grammarSummaryVi: "Câu gián tiếp / Câu tường thuật đối với câu trần thuật (lùi thì, đổi ngôi và trạng từ)",
      vocabularyTheme: "Scientific inventions, discoveries and digital devices",
    },
    {
      unitNumber: 12,
      title: "Life on Other Planets",
      vietnameseTitle: "Sự sống trên các hành tinh khác",
      grammarTopics: ["Reported Speech: Questions (Yes/No and Wh-questions)"],
      grammarSummaryVi: "Câu gián tiếp / Câu tường thuật đối với câu hỏi (asked if/whether, asked wh-...)",
      vocabularyTheme: "Solar system, planets, aliens and space exploration",
    },
  ],
  9: [
    {
      unitNumber: 1,
      title: "Local Community",
      vietnameseTitle: "Cộng đồng địa phương",
      grammarTopics: ["Question words before To-infinitives (what/where/how to do)", "Phrasal Verbs"],
      grammarSummaryVi: "Từ để hỏi đi cùng To-V (what to do, where to go) & Cụm động từ (pass down, run out of...)",
      vocabularyTheme: "Community helpers, artisanal crafts and local services",
    },
    {
      unitNumber: 2,
      title: "City Life",
      vietnameseTitle: "Cuộc sống đô thị",
      grammarTopics: ["Double Comparatives (The + comparative..., the + comparative...)", "Phrasal Verbs"],
      grammarSummaryVi: "So sánh kép 'Càng... càng...' (The more..., the more...) & Cụm động từ",
      vocabularyTheme: "Urban features, public transport and city amenities",
    },
    {
      unitNumber: 3,
      title: "Teen Stress and Pressure",
      vietnameseTitle: "Căng thẳng và áp lực tuổi dậy thì",
      grammarTopics: ["Reported Speech with Question words + To-infinitive", "Modal verbs in reported speech"],
      grammarSummaryVi: "Câu tường thuật với từ để hỏi + To-V & Động từ khuyết thiếu trong câu gián tiếp",
      vocabularyTheme: "Teen emotions, psychological support and coping strategies",
    },
    {
      unitNumber: 4,
      title: "Remembering the Past",
      vietnameseTitle: "Ký ức quá khứ",
      grammarTopics: ["Used to / Didn't use to for past habits", "Wishes for the present (Wish + Past Simple)"],
      grammarSummaryVi: "Cấu trúc Used to chỉ thói quen quá khứ & Câu ước ở hiện tại (S + wish + S + V2/ed)",
      vocabularyTheme: "Traditional games, past lifestyles and preservation of heritage",
    },
    {
      unitNumber: 5,
      title: "Wonders of Viet Nam",
      vietnameseTitle: "Kỳ quan Việt Nam",
      grammarTopics: ["Impersonal Passive (It is said that... / S is claimed to...)", "Suggest + V-ing / (that) S (should) + V"],
      grammarSummaryVi: "Câu bị động không ngôi (It is said that...) & Cấu trúc đưa lời khuyên Suggest",
      vocabularyTheme: "Natural and man-made wonders, ecotourism and heritage",
    },
    {
      unitNumber: 6,
      title: "Viet Nam: Then and Now",
      vietnameseTitle: "Việt Nam: Xưa và nay",
      grammarTopics: ["The Past Perfect (had + V3/ed)", "Adjective + To-infinitive / That-clause"],
      grammarSummaryVi: "Thì Quá khứ hoàn thành (Had + V3/ed) & Tính từ đi kèm To-infinitive / Mệnh đề that",
      vocabularyTheme: "Historical transformations, transport evolution and modern facilities",
    },
    {
      unitNumber: 7,
      title: "Natural Wonders of the World",
      vietnameseTitle: "Kỳ quan thiên nhiên thế giới",
      grammarTopics: ["The Passive Voice: Review across all tenses"],
      grammarSummaryVi: "Câu bị động tổng hợp qua các thì (Present, Past, Future, Modal Verbs)",
      vocabularyTheme: "World natural wonders, geography and conservation",
    },
    {
      unitNumber: 8,
      title: "Tourism",
      vietnameseTitle: "Du lịch",
      grammarTopics: ["Compound Nouns", "Articles: Review of a/an/the/zero article"],
      grammarSummaryVi: "Danh từ ghép (jet lag, package tour, check-in) & Mạo từ xác định / không xác định",
      vocabularyTheme: "Tourism services, holiday types and travel experiences",
    },
    {
      unitNumber: 9,
      title: "World Englishes",
      vietnameseTitle: "Tiếng Anh trên thế giới",
      grammarTopics: ["Defining Relative Clauses (who, whom, which, that, whose)", "Relative clauses with prepositions"],
      grammarSummaryVi: "Mệnh đề quan hệ xác định (who, which, that, whose) & Mệnh đề quan hệ có giới từ",
      vocabularyTheme: "Language varieties, accents, loanwords and bilingualism",
    },
    {
      unitNumber: 10,
      title: "Planet Earth",
      vietnameseTitle: "Hành tinh Trái Đất",
      grammarTopics: ["Non-defining Relative Clauses (which, who, whose)", "Relative Adverbs (where, when, why)"],
      grammarSummaryVi: "Mệnh đề quan hệ không xác định (có dấu phẩy) & Trạng từ quan hệ (where, when, why)",
      vocabularyTheme: "Atmosphere, ecosystems, climate change and celestial bodies",
    },
    {
      unitNumber: 11,
      title: "Electronic Devices",
      vietnameseTitle: "Thiết bị điện tử",
      grammarTopics: ["First and Second Conditional (If loại 1 & loại 2)"],
      grammarSummaryVi: "Câu điều kiện loại 1 & Câu điều kiện loại 2 (If + Past Simple, S + would + V)",
      vocabularyTheme: "Smart gadgets, artificial intelligence and classroom technology",
    },
    {
      unitNumber: 12,
      title: "Career Paths",
      vietnameseTitle: "Định hướng nghề nghiệp",
      grammarTopics: ["Connectors: Despite / In spite of vs Although / Even though", "Verbs + V-ing vs To-infinitive"],
      grammarSummaryVi: "Liên từ tương phản (Despite/In spite of + N/V-ing vs Although + Clause) & V + To-V / V-ing",
      vocabularyTheme: "Professions, soft skills, career requirements and job applications",
    },
  ],
};

/**
 * Helper to get Unit info by grade and unit number
 */
export function getUnitCurriculum(grade: number | string, unitNumber: number): UnitCurriculum | null {
  const gNum = typeof grade === 'number' ? grade : parseInt(String(grade).replace(/\D/g, '')) || 6;
  const list = MOET_CURRICULUM[gNum] || MOET_CURRICULUM[6];
  return list.find(u => u.unitNumber === unitNumber) || null;
}
